// <auto-generated />
using System;
using M3S02_4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M3S02_4.Migrations
{
    [DbContext(typeof(BasicAuthContext))]
    [Migration("20220911205212_MigrationInitial")]
    partial class MigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("M3S02_4.Model.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("073ce8bb-d9be-4f72-9d1d-e7152d58974d"),
                            DataCadastro = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodrigo Paiva"
                        },
                        new
                        {
                            Id = new Guid("901a33b7-9949-4330-832a-aa9bba66db45"),
                            DataCadastro = new DateTime(2022, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rafael Luiz Paiva"
                        },
                        new
                        {
                            Id = new Guid("77da11b5-efc9-466a-abdb-edbb7639016f"),
                            DataCadastro = new DateTime(2022, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Liliane Paiva"
                        });
                });

            modelBuilder.Entity("M3S02_4.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("NomeUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ff37ac0-75bb-4dc9-9cc8-b5259d01088a"),
                            NomeUsuario = "admin",
                            Senha = "123abc456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
