// <auto-generated />
using System;
using M3S02_5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M3S02_5.Migrations
{
    [DbContext(typeof(ApiKeyContext))]
    partial class ApiKeyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("M3S02_5.Model.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ff37ac0-75bb-4dc9-9cc8-b5259d01088a"),
                            ApiKey = "9306B9F1F2B6DB2B2762913D96F0DF4E",
                            Ativo = true,
                            Nome = "Cliente X"
                        },
                        new
                        {
                            Id = new Guid("adc6e73f-0f0a-4acf-97ed-b40af27b108b"),
                            ApiKey = "47933C60BF8A9A41255A86D184B109D3",
                            Ativo = false,
                            Nome = "Cliente Z"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
